# Bird Classification Dataset Configuration
data:
  train_path: "/Users/tianqinmeng/.cache/kagglehub/datasets/kedarsai/bird-species-classification-220-categories/versions/1/Train"
  test_path: "/Users/tianqinmeng/.cache/kagglehub/datasets/kedarsai/bird-species-classification-220-categories/versions/1/Test"
  train_split: 0.8
  val_split: 0.2
  image_size: 224
  batch_size: 32

# Model Configuration
model:
  name: "resnet50"
  num_classes: 220
  pretrained: true
  dropout: 0.5

# Training Configuration
training:
  epochs: 50
  learning_rate: 0.001
  optimizer: "Adam"
  weight_decay: 0.0001
  early_stopping_patience: 10
  save_best_model: true
  batch_size: 32

# MLflow Configuration
mlflow:
  tracking_uri: "file:///Users/tianqinmeng/Desktop/Projects/resnet50-mlops-bird-classifier/mlruns"
  experiment_name: "bird_classification"

# Logging Configuration
logging:
  level: "INFO"
  save_logs: true
  log_dir: "./logs"